In [139]:
# scrap PDF loop data from toby christie's site
# https://tobychristie.com/loop-data-2021-nascar-cup-series/"
# this is v2 of the scraper because there is a different pattern of PDF that tabula could output
# this works for most of the PDFs from the 2021 cup series.
import tabula
import pandas as pd
import re
from tabula import read_pdf
HEADERS_1=["Car","Driver","StartPos","MidRace","CloserPos","FinishPos","HighPos","LowPos", "NumFastestLaps", "LapsLed", "AvgPos","PassDiff","GreenPass","GreenPassed","QualityPasses","PercentQualityPasses", "LapsTop15","PercentLapsTop15", "PercentLapsLed", "TotalLaps","DriverRating","Pts"]
HEADERS_2=["Car","Driver","StartPos","MidRace","CloserPos","FinishPos","HighPos","LowPos","AvgPos","PassDiff","GreenPass","GreenPassed","QualityPasses","PercentQualityPasses","NumFastestLaps","LapsTop15","PercentLapsTop15","LapsLed","PercentLapsLed","TotalLaps","DriverRating","Pts"]
data_location=r"C:\Users\kchen\OneDrive\MADS\SIADS591_592_Milestone1\Milestone_I\data\loop_TobyChristie\pdf\2021\LD12132_POST_POSTBOOK.pdf"
df=read_pdf(data_location,pages='1')

In [140]:
df[0].head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Box Score,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Charlotte Motor Speedway Road Course,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bank of America ROVAL 400,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Provided by NASCAR Statistics at 10/10/2021 5:...,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Green Flag Passes For Lead:1
4,Car,Driver,Start,Mid,Closer,Finish,High,Low,Avg Pass Green Green Quality % Quality # Fastest,Laps in % Laps in,Laps,% Laps Total Driver Pts
5,NaN,NaN,Pos,Race,Pos,Pos,Pos,Pos,Pos Diff Pass Passed Passes Passes Laps,Top 15 Top 15,Led,Led Laps Rating
6,5,Kyle Larson,10,31,2,1,1,37,10.8 77 116 39 39 33.62 16,77 70.6,8,7.3 109 117.6 45
7,8,Tyler Reddick,29,6,3,2,2,38,9.9 1 89 88 40 44.94 13,84 77.1,0,0.0 109 120.2 35
8,17,Chris Buescher,16,8,4,3,1,34,11.3 -2 72 74 34 47.22 2,77 70.6,1,0.9 109 104.9 34
9,18,Kyle Busch,9,21,8,4,1,26,10.5 15 78 63 29 37.18 8,78 71.6,22,20.2 109 108.8 47

C:\Users\kchen\OneDrive\MADS\SIADS591_592_Milestone1\Milestone_I\data\loop_TobyChristie\pdf\2021\LD12133_POST_POSTBOOK.pdf

<ipython-input-141-101250b176d2>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Box Score']=df2['Box Score'].str.split()
<ipython-input-141-101250b176d2>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Unnamed: 9']=df2['Unnamed: 9'].str.split()
<ipython-input-141-101250b176d2>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Unnamed: 11']=df2['Unnamed: 11'].str.split()

C:\Users\kchen\OneDrive\MADS\SIADS591_592_Milestone1\Milestone_I\data\loop_TobyChristie\pdf\2021\LD12134_POST_POSTBOOK.pdf
C:\Users\kchen\OneDrive\MADS\SIADS591_592_Milestone1\Milestone_I\data\loop_TobyChristie\pdf\2021\LD12135_POST_POSTBOOK.pdf
C:\Users\kchen\OneDrive\MADS\SIADS591_592_Milestone1\Milestone_I\data\loop_TobyChristie\pdf\2021\LD12136_POST_POSTBOOK.pdf

In [119]:
fname_track=df[0]['Box Score'][0].replace(" ","")
date_text=df[0]['Box Score'][2]
pattern=r'(\d*)/(\d*)/(\d*)'
fname_year=re.search(pattern,date_text).group(3)
fname_day=re.search(pattern,date_text).group(2).zfill(2)
fname_month=re.search(pattern,date_text).group(1).zfill(2)

In [59]:
df2=df[0].iloc[6:]
df2['Box Score']=df2['Box Score'].str.split()
df2['Unnamed: 9']=df2['Unnamed: 9'].str.split()
df2['Unnamed: 11']=df2['Unnamed: 11'].str.split()

<ipython-input-59-c9aad1a1a6b7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Box Score']=df2['Box Score'].str.split()
<ipython-input-59-c9aad1a1a6b7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Unnamed: 9']=df2['Unnamed: 9'].str.split()
<ipython-input-59-c9aad1a1a6b7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Unnamed: 11']=df2['Unnamed: 11'].str.split()

In [60]:
df2.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Box Score,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
6,20,Christopher Bell,12,3,3,1,1,18,"[6.1, 17, 46, 29, 35, 76.09]",12,"[68, 97.1]",5,"[7.1, 70, 128.8, 47]"
7,22,Joey Logano,11,23,1,2,1,25,"[4.8, 17, 53, 36, 29, 54.72]",3,"[67, 95.7]",10,"[14.3, 70, 121.5, 52]"
8,11,Denny Hamlin,4,1,5,3,1,16,"[4.3, 17, 50, 33, 29, 58]",3,"[70, 100.0]",5,"[7.1, 70, 124.2, 52]"
9,1,Kurt Busch,17,2,2,4,1,29,"[9.2, -3, 73, 76, 27, 36.99]",0,"[54, 77.1]",2,"[2.9, 70, 98.6, 48]"
10,2,Brad Keselowski,15,31,4,5,2,38,"[16.5, -48, 75, 123, 22, 29.33]",0,"[42, 60.0]",0,"[0.0, 70, 76.7, 39]"

In [61]:
df3=pd.DataFrame(df2['Box Score'].tolist(), columns=["AvgPos","PassDiff","GreenPass","GreenPassed","QualityPasses","PercentQualityPasses"])
df4=pd.DataFrame(df2['Unnamed: 9'].tolist(), columns=["LapsTop15","PercentLapsTop15"])
df5=pd.DataFrame(df2['Unnamed: 11'].tolist(), columns=["PercentLapsLed", "TotalLaps","DriverRating","Pts"])

In [62]:
df2=df2[['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6','Unnamed: 7', 'Unnamed: 8','Unnamed: 10']].reset_index(drop=True)

In [63]:
df_final=pd.concat([df2,df3,df4,df5],axis=1)
df_final.columns=HEADERS_1
df_final=df_final[HEADERS_2]

In [64]:
df_final.head(2)

,Car,Driver,StartPos,MidRace,CloserPos,FinishPos,HighPos,LowPos,AvgPos,PassDiff,...,QualityPasses,PercentQualityPasses,NumFastestLaps,LapsTop15,PercentLapsTop15,LapsLed,PercentLapsLed,TotalLaps,DriverRating,Pts
0,20,Christopher Bell,12,3,3,1,1,18,6.1,17,...,35,76.09,12,68,97.1,5,7.1,70,128.8,47
1,22,Joey Logano,11,23,1,2,1,25,4.8,17,...,29,54.72,3,67,95.7,10,14.3,70,121.5,52

In [120]:
r'C:\Users\kchen\OneDrive\MADS\SIADS591_592_Milestone1\Milestone_I\data\loop_TobyChristie\csv\2021\{}.csv'.format(fname_year+fname_month+fname_day+'_'+fname_track)

'C:\\Users\\kchen\\OneDrive\\MADS\\SIADS591_592_Milestone1\\Milestone_I\\data\\loop_TobyChristie\\csv\\2021\\20210228_Homestead-MiamiSpeedway.csv'

In [121]:
df_final.to_csv(r'C:\Users\kchen\OneDrive\MADS\SIADS591_592_Milestone1\Milestone_I\data\loop_TobyChristie\csv\2021\{}.csv'.format(fname_year+fname_month+fname_day+'_'+fname_track),index=False)

In [66]:
df_final.head()

,Car,Driver,AvgStart,AvgMidRace,AvgFinish,Avg Pos,LapsLed,PercentLapsLed,TotalLaps,DriverRating,Pts,PassDiff,GreenPass,GreenPassed,QualityPasses,PercentQualityPasses,NumFastestLaps,LapsinTop15,PercentLapsTop15
0,2,Austin Cindric,5.0,2.0,1.0,6.2,21,10.4,201,122.4,54,-13,168,181,125,74.4,0,176,87.6
1,6,Brad Keselowski,3.0,5.0,9.0,4.8,67,33.3,201,121.3,54,1,171,170,148,86.5,4,198,98.5
2,19,Martin Truex Jr,14.0,18.0,13.0,11.9,11,5.5,201,94.0,49,25,258,233,192,74.4,4,143,71.1
3,23,Bubba Wallace,16.0,19.0,2.0,10.2,12,6.0,201,104.7,47,16,253,237,191,75.5,7,145,72.1
4,14,Chase Briscoe,9.0,10.0,3.0,18.3,0,0.0,201,75.0,41,17,209,192,70,33.5,6,88,43.8

In [67]:
# loop through the whole directory
directory=r'C:\Users\kchen\OneDrive\MADS\SIADS591_592_Milestone1\Milestone_I\data\loop_TobyChristie\pdf\2021'
for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(f):
        # read in data
        df=read_pdf(f,pages='1')
        # get the file name info
        fname_track=df[0]['Box Score'][0].replace(" ","")
        date_text=df[0]['Box Score'][2]
        pattern=r'(\d*)/(\d*)/(\d*)'
        fname_year=re.search(pattern,date_text).group(3)
        fname_day=re.search(pattern,date_text).group(2).zfill(2)
        fname_month=re.search(pattern,date_text).group(1).zfill(2)
        # getting the data cleaned up
        print(f)
        df2=df[0].iloc[6:]
        df2['Box Score']=df2['Box Score'].str.split()
        df2['Unnamed: 9']=df2['Unnamed: 9'].str.split()
        df2['Unnamed: 11']=df2['Unnamed: 11'].str.split()

        # continue to clean
        df3=pd.DataFrame(df2['Box Score'].tolist(), columns=["AvgPos","PassDiff","GreenPass","GreenPassed","QualityPasses","PercentQualityPasses"])
        df4=pd.DataFrame(df2['Unnamed: 9'].tolist(), columns=["LapsTop15","PercentLapsTop15"])
        df5=pd.DataFrame(df2['Unnamed: 11'].tolist(), columns=["PercentLapsLed", "TotalLaps","DriverRating","Pts"])
        
        df2=df2[['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
        'Unnamed: 5', 'Unnamed: 6','Unnamed: 7', 'Unnamed: 8','Unnamed: 10']].reset_index(drop=True)
        
        # final cleaning steps
        df_final=pd.concat([df2,df3,df4,df5],axis=1)
        df_final.columns=HEADERS_1
        df_final=df_final[HEADERS_2]

        # output the data
        df_final.to_csv(r'C:\Users\kchen\OneDrive\MADS\SIADS591_592_Milestone1\Milestone_I\data\loop_TobyChristie\csv\2021\{}.csv'.format(fname_year+fname_month+fname_day+'_'+fname_track),index=False)

(40, 19)