In [2]:
import tabula
import pandas as pd
from tabula import read_pdf
HEADERS=['Car','Driver','AvgStart','AvgMidRace','AvgFinish','Avg Pos','LapsLed','PercentLapsLed','TotalLaps','DriverRating','Pts','PassDiff','GreenPass','GreenPassed','QualityPasses','PercentQualityPasses','NumFastestLaps','LapsinTop15','PercentLapsTop15']
data_location=r"C:\Users\kchen\OneDrive\MADS\SIADS591_592_Milestone1\Milestone_I\Milestone_I\data\loop_TobyChristie\pdf\2022\LD12211_POST_POSTBOOK.pdf"
df=read_pdf(data_location,pages='1')

In [3]:
df[0].head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Box Score,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dover Motor Speedway,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DuraMAX Drydene 400 presented by RelaDyne,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Provided by NASCAR Statistics at 5/2/2022 4:39...,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Green Flag Passes For Lead:2
4,Car,Driver,Start,Mid,Closer,Finish,High,Low Avg Pass Green Green Quality % Quality # F...,Laps in % Laps in,Laps,% Laps Total Driver Pts
5,NaN,NaN,Pos,Race,Pos,Pos,Pos,Pos Pos Diff Pass Passed Passes Passes Laps,Top 15 Top 15,Led,Led Laps Rating
6,9,Chase Elliott,4,8,1,1,1,20 4.1 11 33 22 32 96.97 33,399 99.8,73,18.3 400 132.8 50
7,47,Ricky Stenhouse Jr,15,16,2,2,2,19 8.9 21 59 38 52 88.14 8,376 94.0,0,0.0 400 102.8 41
8,1,Ross Chastain,7,10,3,3,1,20 4.7 14 43 29 42 97.67 38,397 99.3,86,21.5 400 125.2 46
9,20,Christopher Bell,17,30,5,4,2,32 15.3 -2 48 50 18 37.5 13,206 51.5,0,0.0 400 91.5 41

In [4]:
df2=df[0].iloc[5:]
df2['Box Score']=df2['Box Score'].str.split()
df2['Unnamed: 7']=df2['Unnamed: 7'].str.split()
df2['Unnamed: 9']=df2['Unnamed: 9'].str.split()

<ipython-input-4-c4d1a71ad317>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Box Score']=df2['Box Score'].str.split()
<ipython-input-4-c4d1a71ad317>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Unnamed: 7']=df2['Unnamed: 7'].str.split()
<ipython-input-4-c4d1a71ad317>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Unnamed: 9']=df2['Unnamed: 9'].str.split()

In [5]:
df2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Box Score,Unnamed: 7,Unnamed: 8,Unnamed: 9
5,NaN,NaN,Pos,Race,Pos,Pos,Pos,"[Pos, Pos, Diff, Pass, Passed, Passes, Passes,...","[Top, 15, Top, 15]",Led,"[Led, Laps, Rating]"
6,9,Chase Elliott,4,8,1,1,1,"[20, 4.1, 11, 33, 22, 32, 96.97, 33]","[399, 99.8]",73,"[18.3, 400, 132.8, 50]"
7,47,Ricky Stenhouse Jr,15,16,2,2,2,"[19, 8.9, 21, 59, 38, 52, 88.14, 8]","[376, 94.0]",0,"[0.0, 400, 102.8, 41]"
8,1,Ross Chastain,7,10,3,3,1,"[20, 4.7, 14, 43, 29, 42, 97.67, 38]","[397, 99.3]",86,"[21.5, 400, 125.2, 46]"
9,20,Christopher Bell,17,30,5,4,2,"[32, 15.3, -2, 48, 50, 18, 37.5, 13]","[206, 51.5]",0,"[0.0, 400, 91.5, 41]"
10,48,Alex Bowman,6,3,8,5,1,"[18, 6.8, 5, 33, 28, 33, 100, 24]","[393, 98.3]",2,"[0.5, 400, 109.1, 40]"
11,5,Kyle Larson,3,28,7,6,1,"[31, 10.3, 14, 48, 34, 29, 60.42, 15]","[309, 77.3]",19,"[4.8, 400, 99.6, 36]"
12,18,Kyle Busch,10,6,10,7,1,"[17, 5.9, 22, 61, 39, 56, 91.8, 35]","[390, 97.5]",103,"[25.8, 400, 120.7, 41]"
13,17,Chris Buescher,1,15,9,8,1,"[17, 7.9, 4, 36, 32, 33, 91.67, 10]","[375, 93.8]",18,"[4.5, 400, 101.6, 34]"
14,4,Kevin Harvick,11,14,13,9,7,"[24, 11.5, 18, 60, 42, 58, 96.67, 5]","[385, 96.3]",0,"[0.0, 400, 90.6, 28]"
15,43,Erik Jones,25,18,6,10,3,"[25, 13.2, 8, 55, 47, 24, 43.64, 1]","[260, 65.0]",0,"[0.0, 400, 82.2, 31]"
16,31,Justin Haley,14,1,12,11,1,"[25, 12.7, -27, 34, 61, 23, 67.65, 6]","[287, 71.8]",19,"[4.8, 400, 82.3, 26]"
17,19,Martin Truex Jr,18,12,4,12,1,"[22, 6.3, 11, 40, 29, 33, 82.5, 56]","[343, 85.8]",5,"[1.3, 400, 104.7, 38]"
18,14,Chase Briscoe,23,21,16,13,5,"[29, 21.6, 4, 59, 55, 10, 16.95, 1]","[69, 17.3]",0,"[0.0, 400, 60.6, 24]"
19,99,Daniel Suárez,8,7,14,14,6,"[29, 16.1, -9, 75, 84, 38, 50.67, 1]","[222, 55.5]",0,"[0.0, 400, 66.1, 23]"
20,41,Cole Custer,30,24,15,15,14,"[32, 24.8, 5, 62, 57, 12, 19.35, 0]","[30, 7.5]",0,"[0.0, 400, 52.5, 22]"
21,23,Bubba Wallace,9,4,11,16,4,"[27, 15.2, -16, 45, 61, 22, 48.89, 1]","[188, 47.0]",0,"[0.0, 399, 66.6, 21]"
22,34,Michael McDowell,29,25,17,17,10,"[32, 22.0, 6, 53, 47, 8, 15.09, 0]","[58, 14.5]",0,"[0.0, 399, 54.5, 20]"
23,7,Corey Lajoie,21,20,18,18,12,"[27, 19.7, -8, 43, 51, 7, 16.28, 1]","[47, 11.8]",0,"[0.0, 399, 55.6, 19]"
24,10,Aric Almirola,27,22,19,19,5,"[27, 16.5, -3, 52, 55, 15, 28.85, 1]","[179, 44.8]",0,"[0.0, 399, 62.9, 18]"
25,6,Brad Keselowski,20,23,20,20,4,"[25, 15.9, -7, 48, 55, 17, 35.42, 1]","[180, 45.0]",0,"[0.0, 399, 65.7, 18]"
26,11,Denny Hamlin,2,17,22,21,1,"[29, 14.2, 50, 77, 27, 35, 45.45, 42]","[198, 49.5]",67,"[16.8, 399, 86.2, 26]"
27,24,William Byron,33,9,23,22,4,"[33, 15.4, -4, 47, 51, 19, 40.43, 3]","[208, 52.0]",0,"[0.0, 399, 68.2, 19]"
28,3,Austin Dillon,24,11,24,23,6,"[29, 25.4, -38, 21, 59, 2, 9.52, 0]","[14, 3.5]",0,"[0.0, 398, 44.0, 14]"
29,21,Harrison Burton,35,26,25,24,2,"[35, 27.5, -5, 45, 50, 0, 0, 0]","[9, 2.3]",0,"[0.0, 398, 41.0, 16]"
30,15,Ryan Preece,13,27,21,25,13,"[28, 20.2, -5, 66, 71, 1, 1.52, 4]","[18, 4.5]",0,"[0.0, 398, 59.1, 0]"
31,12,Ryan Blaney,5,19,26,26,1,"[29, 17.7, 2, 40, 38, 8, 20, 3]","[131, 32.8]",8,"[2.0, 397, 67.6, 21]"
32,42,Ty Dillon,31,13,28,27,8,"[33, 28.7, -22, 24, 46, 4, 16.67, 0]","[11, 2.8]",0,"[0.0, 396, 38.3, 10]"
33,38,Todd Gilliland,34,31,27,28,27,"[35, 31.7, -4, 8, 12, 0, 0, 0]","[0, 0.0]",0,"[0.0, 396, 34.0, 9]"
34,22,Joey Logano,22,29,29,29,11,"[31, 26.4, -5, 29, 34, 0, 0, 0]","[3, 0.8]",0,"[0.0, 396, 39.5, 8]"
35,8,Tyler Reddick,26,5,30,30,4,"[30, 22.1, -12, 60, 72, 5, 8.33, 1]","[43, 10.8]",0,"[0.0, 390, 43.4, 7]"
36,45,Kurt Busch,16,32,31,31,7,"[33, 25.8, 6, 34, 28, 3, 8.82, 4]","[19, 4.8]",0,"[0.0, 388, 43.7, 6]"
37,77,Josh Bilicki,36,34,32,32,32,"[36, 34.1, -3, 1, 4, 0, 0, 0]","[0, 0.0]",0,"[0.0, 381, 26.7, 0]"
38,16,AJ Allmendinger,19,2,33,33,2,"[31, 18.9, -21, 47, 68, 18, 38.3, 4]","[179, 44.8]",0,"[0.0, 321, 62.6, 0]"
39,51,Cody Ware,28,33,34,34,26,"[33, 32.9, -3, 11, 14, 0, 0, 0]","[0, 0.0]",0,"[0.0, 238, 31.8, 3]"
40,78,BJ McLeod,32,35,35,35,32,"[36, 34.7, 3, 5, 2, 0, 0, 0]","[0, 0.0]",0,"[0.0, 167, 24.8, 2]"
41,2,Austin Cindric,12,36,36,36,6,"[36, 30.9, -4, 9, 13, 4, 44.44, 1]","[74, 18.5]",0,"[0.0, 91, 46.9, 1]"

In [44]:
df3=pd.DataFrame(df2['Box Score'].tolist(), columns=['PassDiff','GreenPass','GreenPassed','QualityPasses','PercentQualityPasses','NumFastestLaps'])
df4=pd.DataFrame(df2['Unnamed: 6'].tolist(), columns=['LapsinTop15','PercentLapsTop15'])

In [52]:
df2=df2[['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11']]

(40, 11)

In [54]:
df2=df2.reset_index(drop=True)
df_final=pd.concat([df2,df3,df4],axis=1)
df_final.columns=HEADERS

(40, 2)

In [66]:
df_final.head()

,Car,Driver,AvgStart,AvgMidRace,AvgFinish,Avg Pos,LapsLed,PercentLapsLed,TotalLaps,DriverRating,Pts,PassDiff,GreenPass,GreenPassed,QualityPasses,PercentQualityPasses,NumFastestLaps,LapsinTop15,PercentLapsTop15
0,2,Austin Cindric,5.0,2.0,1.0,6.2,21,10.4,201,122.4,54,-13,168,181,125,74.4,0,176,87.6
1,6,Brad Keselowski,3.0,5.0,9.0,4.8,67,33.3,201,121.3,54,1,171,170,148,86.5,4,198,98.5
2,19,Martin Truex Jr,14.0,18.0,13.0,11.9,11,5.5,201,94.0,49,25,258,233,192,74.4,4,143,71.1
3,23,Bubba Wallace,16.0,19.0,2.0,10.2,12,6.0,201,104.7,47,16,253,237,191,75.5,7,145,72.1
4,14,Chase Briscoe,9.0,10.0,3.0,18.3,0,0.0,201,75.0,41,17,209,192,70,33.5,6,88,43.8

In [67]:
df_final.shape

(40, 19)